<?php
/**
 * SearchApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lite API
 *
 * The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * SearchApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'hotelsGet' => [
            'application/json',
        ],
        'hotelsRatesGet' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation hotelsGet
     *
     * hotel minimum rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['hotelsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object|object|object|object
     */
    public function hotelsGet($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['hotelsGet'][0])
    {
        list($response) = $this->hotelsGetWithHttpInfo($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children, $guest_id, $contentType);
        return $response;
    }

    /**
     * Operation hotelsGetWithHttpInfo
     *
     * hotel minimum rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['hotelsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object|object|object|object, HTTP status code, HTTP response headers (array of strings)
     */
    public function hotelsGetWithHttpInfo($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['hotelsGet'][0])
    {
        $request = $this->hotelsGetRequest($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children, $guest_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 204:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 204:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation hotelsGetAsync
     *
     * hotel minimum rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['hotelsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function hotelsGetAsync($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['hotelsGet'][0])
    {
        return $this->hotelsGetAsyncWithHttpInfo($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children, $guest_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation hotelsGetAsyncWithHttpInfo
     *
     * hotel minimum rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['hotelsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function hotelsGetAsyncWithHttpInfo($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['hotelsGet'][0])
    {
        $returnType = 'object';
        $request = $this->hotelsGetRequest($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children, $guest_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'hotelsGet'
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['hotelsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function hotelsGetRequest($hotel_ids, $checkin, $checkout, $currency, $guest_nationality, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['hotelsGet'][0])
    {

        // verify the required parameter 'hotel_ids' is set
        if ($hotel_ids === null || (is_array($hotel_ids) && count($hotel_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $hotel_ids when calling hotelsGet'
            );
        }

        // verify the required parameter 'checkin' is set
        if ($checkin === null || (is_array($checkin) && count($checkin) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $checkin when calling hotelsGet'
            );
        }

        // verify the required parameter 'checkout' is set
        if ($checkout === null || (is_array($checkout) && count($checkout) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $checkout when calling hotelsGet'
            );
        }

        // verify the required parameter 'currency' is set
        if ($currency === null || (is_array($currency) && count($currency) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $currency when calling hotelsGet'
            );
        }

        // verify the required parameter 'guest_nationality' is set
        if ($guest_nationality === null || (is_array($guest_nationality) && count($guest_nationality) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guest_nationality when calling hotelsGet'
            );
        }

        // verify the required parameter 'adults' is set
        if ($adults === null || (is_array($adults) && count($adults) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $adults when calling hotelsGet'
            );
        }




        $resourcePath = '/hotels';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $hotel_ids,
            'hotelIds', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $checkin,
            'checkin', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $checkout,
            'checkout', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $currency,
            'currency', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $guest_nationality,
            'guestNationality', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $adults,
            'adults', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $children,
            'children', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $guest_id,
            'guestId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation hotelsRatesGet
     *
     * hotel full rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['hotelsRatesGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object|object|object
     */
    public function hotelsRatesGet($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['hotelsRatesGet'][0])
    {
        list($response) = $this->hotelsRatesGetWithHttpInfo($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children, $guest_id, $contentType);
        return $response;
    }

    /**
     * Operation hotelsRatesGetWithHttpInfo
     *
     * hotel full rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['hotelsRatesGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object|object|object, HTTP status code, HTTP response headers (array of strings)
     */
    public function hotelsRatesGetWithHttpInfo($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['hotelsRatesGet'][0])
    {
        $request = $this->hotelsRatesGetRequest($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children, $guest_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 204:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 204:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation hotelsRatesGetAsync
     *
     * hotel full rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['hotelsRatesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function hotelsRatesGetAsync($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['hotelsRatesGet'][0])
    {
        return $this->hotelsRatesGetAsyncWithHttpInfo($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children, $guest_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation hotelsRatesGetAsyncWithHttpInfo
     *
     * hotel full rates availability
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['hotelsRatesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function hotelsRatesGetAsyncWithHttpInfo($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['hotelsRatesGet'][0])
    {
        $returnType = 'object';
        $request = $this->hotelsRatesGetRequest($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children, $guest_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'hotelsRatesGet'
     *
     * @param  string $hotel_ids List of hotelIds (required)
     * @param  string $checkin Check in data in YYYY-MM-DD format (required)
     * @param  string $checkout Check out data in YYYY-MM-DD format (required)
     * @param  string $guest_nationality Guest nationality ISO-2 code - example (SG) (required)
     * @param  string $currency Currency code - example (USD) (required)
     * @param  int $adults Number of adult guests staying (required)
     * @param  string $children Number of children staying if any (optional)
     * @param  string $guest_id Unique traveler ID if available (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['hotelsRatesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function hotelsRatesGetRequest($hotel_ids, $checkin, $checkout, $guest_nationality, $currency, $adults, $children = null, $guest_id = null, string $contentType = self::contentTypes['hotelsRatesGet'][0])
    {

        // verify the required parameter 'hotel_ids' is set
        if ($hotel_ids === null || (is_array($hotel_ids) && count($hotel_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $hotel_ids when calling hotelsRatesGet'
            );
        }

        // verify the required parameter 'checkin' is set
        if ($checkin === null || (is_array($checkin) && count($checkin) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $checkin when calling hotelsRatesGet'
            );
        }

        // verify the required parameter 'checkout' is set
        if ($checkout === null || (is_array($checkout) && count($checkout) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $checkout when calling hotelsRatesGet'
            );
        }

        // verify the required parameter 'guest_nationality' is set
        if ($guest_nationality === null || (is_array($guest_nationality) && count($guest_nationality) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guest_nationality when calling hotelsRatesGet'
            );
        }

        // verify the required parameter 'currency' is set
        if ($currency === null || (is_array($currency) && count($currency) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $currency when calling hotelsRatesGet'
            );
        }

        // verify the required parameter 'adults' is set
        if ($adults === null || (is_array($adults) && count($adults) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $adults when calling hotelsRatesGet'
            );
        }




        $resourcePath = '/hotels/rates';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $hotel_ids,
            'hotelIds', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $checkin,
            'checkin', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $checkout,
            'checkout', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $guest_nationality,
            'guestNationality', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $currency,
            'currency', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $adults,
            'adults', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $children,
            'children', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $guest_id,
            'guestId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
