<?php
/**
 * RatesBookPostRequestGuestInfo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LiteAPI
 * @author   liteAPI Generator team
 * @link     https://www.liteapi.travel
 */

/**
 * liteAPI
 *
 * The **liteAPI** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the liteAPI document: 2.0.0
 * Generated by: https://www.liteapi.travel
 * liteAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by liteAPI Generator (https://www.liteapi.travel).
 * https://www.liteapi.travel
 * Do not edit the class manually.
 */

namespace LiteAPI\Model;

use \ArrayAccess;
use \LiteAPI\ObjectSerializer;

/**
 * RatesBookPostRequestGuestInfo Class Doc Comment
 *
 * @category Class
 * @package  LiteAPI
 * @author   liteAPI Generator team
 * @link     https://www.liteapi.travel
 * @implements \ArrayAccess<string, mixed>
 */
class RatesBookPostRequestGuestInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_rates_book_post_request_guestInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'guest_first_name' => 'string',
        'guest_last_name' => 'string',
        'guest_email' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'guest_first_name' => null,
        'guest_last_name' => null,
        'guest_email' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'guest_first_name' => false,
		'guest_last_name' => false,
		'guest_email' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'guest_first_name' => 'guestFirstName',
        'guest_last_name' => 'guestLastName',
        'guest_email' => 'guestEmail'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'guest_first_name' => 'setGuestFirstName',
        'guest_last_name' => 'setGuestLastName',
        'guest_email' => 'setGuestEmail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'guest_first_name' => 'getGuestFirstName',
        'guest_last_name' => 'getGuestLastName',
        'guest_email' => 'getGuestEmail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('guest_first_name', $data ?? [], null);
        $this->setIfExists('guest_last_name', $data ?? [], null);
        $this->setIfExists('guest_email', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['guest_first_name'] === null) {
            $invalidProperties[] = "'guest_first_name' can't be null";
        }
        if ($this->container['guest_last_name'] === null) {
            $invalidProperties[] = "'guest_last_name' can't be null";
        }
        if ($this->container['guest_email'] === null) {
            $invalidProperties[] = "'guest_email' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets guest_first_name
     *
     * @return string
     */
    public function getGuestFirstName()
    {
        return $this->container['guest_first_name'];
    }

    /**
     * Sets guest_first_name
     *
     * @param string $guest_first_name traveler first name
     *
     * @return self
     */
    public function setGuestFirstName($guest_first_name)
    {
        if (is_null($guest_first_name)) {
            throw new \InvalidArgumentException('non-nullable guest_first_name cannot be null');
        }
        $this->container['guest_first_name'] = $guest_first_name;

        return $this;
    }

    /**
     * Gets guest_last_name
     *
     * @return string
     */
    public function getGuestLastName()
    {
        return $this->container['guest_last_name'];
    }

    /**
     * Sets guest_last_name
     *
     * @param string $guest_last_name traveler last name
     *
     * @return self
     */
    public function setGuestLastName($guest_last_name)
    {
        if (is_null($guest_last_name)) {
            throw new \InvalidArgumentException('non-nullable guest_last_name cannot be null');
        }
        $this->container['guest_last_name'] = $guest_last_name;

        return $this;
    }

    /**
     * Gets guest_email
     *
     * @return string
     */
    public function getGuestEmail()
    {
        return $this->container['guest_email'];
    }

    /**
     * Sets guest_email
     *
     * @param string $guest_email traveler email
     *
     * @return self
     */
    public function setGuestEmail($guest_email)
    {
        if (is_null($guest_email)) {
            throw new \InvalidArgumentException('non-nullable guest_email cannot be null');
        }
        $this->container['guest_email'] = $guest_email;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


