<?php
/**
 * RateBook200ResponseData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * nlite API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * RateBook200ResponseData Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RateBook200ResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'rateBook_200_response_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'booked_rooms' => '\OpenAPI\Client\Model\RateBook200ResponseDataBookedRoomsInner[]',
        'booking_id' => 'string',
        'cancellation' => '\OpenAPI\Client\Model\RateBook200ResponseDataCancellation',
        'cancellation_policies' => '\OpenAPI\Client\Model\RateBook200ResponseDataCancellationPolicies',
        'contact' => '\OpenAPI\Client\Model\RateBook200ResponseDataContact',
        'created_at' => 'string',
        'end' => 'string',
        'hotel' => '\OpenAPI\Client\Model\RateBook200ResponseDataHotel',
        'hotel_confirmation_code' => 'string',
        'notes' => '\OpenAPI\Client\Model\RateBook200ResponseDataNotes',
        'start' => 'string',
        'status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'booked_rooms' => null,
        'booking_id' => null,
        'cancellation' => null,
        'cancellation_policies' => null,
        'contact' => null,
        'created_at' => null,
        'end' => null,
        'hotel' => null,
        'hotel_confirmation_code' => null,
        'notes' => null,
        'start' => null,
        'status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'booked_rooms' => false,
		'booking_id' => false,
		'cancellation' => false,
		'cancellation_policies' => false,
		'contact' => false,
		'created_at' => false,
		'end' => false,
		'hotel' => false,
		'hotel_confirmation_code' => false,
		'notes' => false,
		'start' => false,
		'status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'booked_rooms' => 'bookedRooms',
        'booking_id' => 'bookingId',
        'cancellation' => 'cancellation',
        'cancellation_policies' => 'cancellationPolicies',
        'contact' => 'contact',
        'created_at' => 'createdAt',
        'end' => 'end',
        'hotel' => 'hotel',
        'hotel_confirmation_code' => 'hotelConfirmationCode',
        'notes' => 'notes',
        'start' => 'start',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'booked_rooms' => 'setBookedRooms',
        'booking_id' => 'setBookingId',
        'cancellation' => 'setCancellation',
        'cancellation_policies' => 'setCancellationPolicies',
        'contact' => 'setContact',
        'created_at' => 'setCreatedAt',
        'end' => 'setEnd',
        'hotel' => 'setHotel',
        'hotel_confirmation_code' => 'setHotelConfirmationCode',
        'notes' => 'setNotes',
        'start' => 'setStart',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'booked_rooms' => 'getBookedRooms',
        'booking_id' => 'getBookingId',
        'cancellation' => 'getCancellation',
        'cancellation_policies' => 'getCancellationPolicies',
        'contact' => 'getContact',
        'created_at' => 'getCreatedAt',
        'end' => 'getEnd',
        'hotel' => 'getHotel',
        'hotel_confirmation_code' => 'getHotelConfirmationCode',
        'notes' => 'getNotes',
        'start' => 'getStart',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('booked_rooms', $data ?? [], null);
        $this->setIfExists('booking_id', $data ?? [], null);
        $this->setIfExists('cancellation', $data ?? [], null);
        $this->setIfExists('cancellation_policies', $data ?? [], null);
        $this->setIfExists('contact', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('end', $data ?? [], null);
        $this->setIfExists('hotel', $data ?? [], null);
        $this->setIfExists('hotel_confirmation_code', $data ?? [], null);
        $this->setIfExists('notes', $data ?? [], null);
        $this->setIfExists('start', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets booked_rooms
     *
     * @return \OpenAPI\Client\Model\RateBook200ResponseDataBookedRoomsInner[]|null
     */
    public function getBookedRooms()
    {
        return $this->container['booked_rooms'];
    }

    /**
     * Sets booked_rooms
     *
     * @param \OpenAPI\Client\Model\RateBook200ResponseDataBookedRoomsInner[]|null $booked_rooms booked_rooms
     *
     * @return self
     */
    public function setBookedRooms($booked_rooms)
    {

        if (is_null($booked_rooms)) {
            throw new \InvalidArgumentException('non-nullable booked_rooms cannot be null');
        }

        $this->container['booked_rooms'] = $booked_rooms;

        return $this;
    }

    /**
     * Gets booking_id
     *
     * @return string|null
     */
    public function getBookingId()
    {
        return $this->container['booking_id'];
    }

    /**
     * Sets booking_id
     *
     * @param string|null $booking_id booking_id
     *
     * @return self
     */
    public function setBookingId($booking_id)
    {

        if (is_null($booking_id)) {
            throw new \InvalidArgumentException('non-nullable booking_id cannot be null');
        }

        $this->container['booking_id'] = $booking_id;

        return $this;
    }

    /**
     * Gets cancellation
     *
     * @return \OpenAPI\Client\Model\RateBook200ResponseDataCancellation|null
     */
    public function getCancellation()
    {
        return $this->container['cancellation'];
    }

    /**
     * Sets cancellation
     *
     * @param \OpenAPI\Client\Model\RateBook200ResponseDataCancellation|null $cancellation cancellation
     *
     * @return self
     */
    public function setCancellation($cancellation)
    {

        if (is_null($cancellation)) {
            throw new \InvalidArgumentException('non-nullable cancellation cannot be null');
        }

        $this->container['cancellation'] = $cancellation;

        return $this;
    }

    /**
     * Gets cancellation_policies
     *
     * @return \OpenAPI\Client\Model\RateBook200ResponseDataCancellationPolicies|null
     */
    public function getCancellationPolicies()
    {
        return $this->container['cancellation_policies'];
    }

    /**
     * Sets cancellation_policies
     *
     * @param \OpenAPI\Client\Model\RateBook200ResponseDataCancellationPolicies|null $cancellation_policies cancellation_policies
     *
     * @return self
     */
    public function setCancellationPolicies($cancellation_policies)
    {

        if (is_null($cancellation_policies)) {
            throw new \InvalidArgumentException('non-nullable cancellation_policies cannot be null');
        }

        $this->container['cancellation_policies'] = $cancellation_policies;

        return $this;
    }

    /**
     * Gets contact
     *
     * @return \OpenAPI\Client\Model\RateBook200ResponseDataContact|null
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param \OpenAPI\Client\Model\RateBook200ResponseDataContact|null $contact contact
     *
     * @return self
     */
    public function setContact($contact)
    {

        if (is_null($contact)) {
            throw new \InvalidArgumentException('non-nullable contact cannot be null');
        }

        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {

        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }

        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets end
     *
     * @return string|null
     */
    public function getEnd()
    {
        return $this->container['end'];
    }

    /**
     * Sets end
     *
     * @param string|null $end end
     *
     * @return self
     */
    public function setEnd($end)
    {

        if (is_null($end)) {
            throw new \InvalidArgumentException('non-nullable end cannot be null');
        }

        $this->container['end'] = $end;

        return $this;
    }

    /**
     * Gets hotel
     *
     * @return \OpenAPI\Client\Model\RateBook200ResponseDataHotel|null
     */
    public function getHotel()
    {
        return $this->container['hotel'];
    }

    /**
     * Sets hotel
     *
     * @param \OpenAPI\Client\Model\RateBook200ResponseDataHotel|null $hotel hotel
     *
     * @return self
     */
    public function setHotel($hotel)
    {

        if (is_null($hotel)) {
            throw new \InvalidArgumentException('non-nullable hotel cannot be null');
        }

        $this->container['hotel'] = $hotel;

        return $this;
    }

    /**
     * Gets hotel_confirmation_code
     *
     * @return string|null
     */
    public function getHotelConfirmationCode()
    {
        return $this->container['hotel_confirmation_code'];
    }

    /**
     * Sets hotel_confirmation_code
     *
     * @param string|null $hotel_confirmation_code hotel_confirmation_code
     *
     * @return self
     */
    public function setHotelConfirmationCode($hotel_confirmation_code)
    {

        if (is_null($hotel_confirmation_code)) {
            throw new \InvalidArgumentException('non-nullable hotel_confirmation_code cannot be null');
        }

        $this->container['hotel_confirmation_code'] = $hotel_confirmation_code;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return \OpenAPI\Client\Model\RateBook200ResponseDataNotes|null
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param \OpenAPI\Client\Model\RateBook200ResponseDataNotes|null $notes notes
     *
     * @return self
     */
    public function setNotes($notes)
    {

        if (is_null($notes)) {
            throw new \InvalidArgumentException('non-nullable notes cannot be null');
        }

        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets start
     *
     * @return string|null
     */
    public function getStart()
    {
        return $this->container['start'];
    }

    /**
     * Sets start
     *
     * @param string|null $start start
     *
     * @return self
     */
    public function setStart($start)
    {

        if (is_null($start)) {
            throw new \InvalidArgumentException('non-nullable start cannot be null');
        }

        $this->container['start'] = $start;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {

        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }

        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


