<?php
/**
 * HotelsHotelIdGet200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lite API
 *
 * lite api hotel booking api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * HotelsHotelIdGet200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesTest Class Doc Comment
 *
 * @category    Class
 * @description HotelsHotelIdGet200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class HotelsHotelIdGet200ResponseDataRoomTypesInnerRatesInnerCancellationPoliciesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HotelsHotelIdGet200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies"
     */
    public function testHotelsHotelIdGet200ResponseDataRoomTypesInnerRatesInnerCancellationPolicies()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cancel_policy_infos"
     */
    public function testPropertyCancelPolicyInfos()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hotel_remarks"
     */
    public function testPropertyHotelRemarks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "refundable_tag"
     */
    public function testPropertyRefundableTag()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
