<?php
/**
 * RatesBookPostRequestPaymentTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LiteAPI
 * @author   liteAPI Generator team
 * @link     https://www.liteapi.travel
 */

/**
 * liteAPI
 *
 * The **liteAPI** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 */

/**
 * NOTE: This class is auto generated by liteAPI Generator (https://www.liteapi.travel).
 * https://www.liteapi.travel
 * Please update the test case below to test the model.
 */

namespace LiteAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RatesBookPostRequestPaymentTest Class Doc Comment
 *
 * @category    Class
 * @description RatesBookPostRequestPayment
 * @package     LiteAPI
 * @author      liteAPI Generator team
 * @link        https://www.liteapi.travel
 */
class RatesBookPostRequestPaymentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RatesBookPostRequestPayment"
     */
    public function testRatesBookPostRequestPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "holder_name"
     */
    public function testPropertyHolderName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expire_date"
     */
    public function testPropertyExpireDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cvc"
     */
    public function testPropertyCvc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
