<?php

/**
 * BookingsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * nlite API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use PHPUnit\Framework\TestCase;
use \OpenAPI\Client\Api\BookingsApi;
use GuzzleHttp\Client;

/**
 * BookingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BookingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $config = Configuration::getDefaultConfiguration();
        $this->apiInstance = new BookingsApi(
            new Client(),
            $config
        );
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bookingCancel
     *
     * booking cancel.
     *
     */
    // public function testBookingCancel()
    // {
    //     // TODO: implement
    //     $this->markTestIncomplete('Not implemented');
    // }

    /**
     * Test case for bookingRetrieve
     *
     * booking retrieve.
     *
     */
    // public function testBookingRetrieve()
    // {
    //     // TODO: implement
    //     $this->markTestIncomplete('Not implemented');
    // }

    /**
     * Test case for rateBook
     *
     * rate book.
     *
     */
    public function testRateBook()
    {
        try {
            $body = [
                "prebookId" => "puV0C6Ygs",
                "sessionId" => "GIYDEMZNGAZS2MJVPQZDAMRTFUYDGLJRGZ6DC7BRGIWDS7CNIF6HYMLEMRWV6Z3EKNXGC",
                "contact" => [
                    "firstName" => "fname",
                    "lastName" => "lname",
                    "email" => "test@test.com"
                ],
                "rateId" => "2_4AJJDS635YOKR4HO6LMEPTCNH5MO3ALKOOQBIMRW7XM6UMOC7TNFPJPYOJTLBUVMWP4DSI4DMQNFFAEK6FTLTHKJNQNII5UOO6W55T6K3LOV6ZITOYPQZQEVPF4N3TWJU6TWHWN4Y7CKLRH2C76D6BGZXFC7LPS2DNZGL7O2RPEJMI63YVXLEQ7W3LFOW7ZODW7QNEZ2YXELDO45EOFOSJ42ILLHVIK6HGRGRYR4FXKBBUDZ7YK4AQKASIZQWKMZOH5AIB7VDGTHBM44DJBCO47V5DVNP2UBC3QZ22GMGB7MZMGSAZN5ETAYIKH3HERCAU7SJQWGTRDM7S5Z6U7EBK53AC2RHUJIRULDB5KUPIFSOAAIVOIM7OORIWPDA23HXSLWFE6QWMXUJUSK6TRUOY7SKXBNJTHYUTNAQAVUOHXHCKATM6SWHLZL677ZZ4PCR4IFTRENFD6TDTNTXLAIATQVTAFUQPQQDJML3R57YWCXZPP7CCVJ244ZX2ZBJ3XAJCTDWLVJF3RVV5J3AJYYMFY"
            ];
            $result = $this->apiInstance->bookPost($body);
            $this->assertIsObject($result);
        } catch (\Exception $e) {
            echo 'Exception when calling DefaultApi::hotelsData() : ', $e->getMessage(), PHP_EOL;
        }
    }

    /**
     * Test case for ratePrebook
     *
     * rate prebook.
     *
     */
    public function testRatePrebook()
    {
        try {
            $body = [
                "sessionId" => "GIYDEMZNGAZS2MJVPQZDAMRTFUYDGLJRGZ6DC7BRGIWDS7CNIF6HYMLEMRWV6Z3EKNXGC",
                "rateId" => "2_4AJJDS635YOKR4HO6LMEPTCNH5MO3ALKOOQBIMRW7XM6UMOC7TNFPJPYOJTLBUVMWP4DSI4DMQNFFAEK6FTLTHKJNQNII5UOO6W55T6K3LOV6ZITOYPQZQEVPF4N3TWJU6TWHWN4Y7CKLRH2C76D6BGZXFC7LPS2DNZGL7O2RPEJMI63YVXLEQ7W3LFOW7ZODW7QNEZ2YXELDO45EOFOSJ42ILLHVIK6HGRGRYR4FXKBBUDZ7YK4AQKASIZQWKMZOH5AIB7VDGTHBM44DJBCO47V5DVNP2UBC3QZ22GMGB7MZMGSAZN5ETAYIKH3HERCAU7SJQWGTRDM7S5Z6U7EBK53AC2RHUJIRULDB5KUPIFSOAAIVOIM7OORIWPDA23HXSLWFE6QWMXUJUSK6TRUOY7SKXBNJTHYUTNAQAVUOHXHCKATM6SWHLZL677ZZ4PCR4IFTRENFD6TDTNTXLAIATQVTAFUQPQQDJML3R57YWCXZPP7CCVJ244ZX2ZBJ3XAJCTDWLVJF3RVV5J3AJYYMFY"
            ];
            $result = $this->apiInstance->prebookPost($body);
            $this->assertIsObject($result);
        } catch (\Exception $e) {
            echo 'Exception when calling DefaultApi::hotelsData() : ', $e->getMessage(), PHP_EOL;
        }
    }
}
