<?php

/**
 * HotelsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * nlite API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use PHPUnit\Framework\TestCase;


use \OpenAPI\Client\Api\HotelsApi;
use \OpenAPI\Client\Model\HotelsPostRequest;
use GuzzleHttp\Client;

/**
 * HotelsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HotelsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $config = Configuration::getDefaultConfiguration();
        $this->apiInstance = new HotelsApi(
            new Client(),
            $config
        );
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for hotelRates
     *
     * hotel rates.
     *
     */
    public function testHotelRates()
    {
        try {
            $data = [
                "checkin" => "2023-01-15",
                "checkout" => "2023-01-16",
                "latitude" => 41.009336416923006,
                "longitude" => 28.96179423827173,
                "country" => "TR",
                "distance" => 50,
                "adults" => 1,
                "currency" => "EUR",
                "guest_nationality" => "MA"
            ];
            $hotelsRequest = new HotelsPostRequest($data);
            $result = $this->apiInstance->hotelsPost(null, $hotelsRequest);
            $this->assertIsObject($result);
        } catch (\Exception $e) {
            echo 'Exception when calling DefaultApi::hotelsData() : ', $e->getMessage(), PHP_EOL;
        }
    }

    /**
     * Test case for hotelsSearch
     *
     * hotels search.
     *
     */
    public function testHotelsSearch()
    {
        try {
            $hotel_id = 57871;
            $checkin = "2023-03-15";
            $checkout = "2023-03-16";
            $adults = 1;
            $guest_nationality = "MA";
            $currency = "USD";
            $result = $this->apiInstance->hotelsHotelIdGet($hotel_id, null, null, $checkin, $checkout, $adults, $guest_nationality, $currency);
            $this->assertIsObject($result);
        } catch (\Exception $e) {
            echo 'Exception when calling DefaultApi::hotelsData() : ', $e->getMessage(), PHP_EOL;
        }
    }
}
